### ISSUE TITLE
iContact "client folder" selection ? 

### ISSUE THREAD

**Issue by benborie** [katzwebservices/Gravity-Forms-iContact#11]
Hi, we use "client folders" on our iContact account (this feature is used by agencies with multiple clients).

The plugin will pull lists only from our most recent client folder - not the one we were hoping to connect to. 

Do you know of a fix for this situation ?

**Comment by benborie** [comment]
So the solution was fairly simple if you hardcode a single client folder:

In:
/wp-content/plugins/gravity-forms-icontact/api/iContact.class.php line 43
Replace: 
$this->clientFolderId = empty($settings['clientfolderid']) ? $this->getClientFolderId() : $settings['clientfolderid'];
With: 
$this->clientFolderId = xxxx;

Where xxxx is your client folder id. 

Hope this helps someone...

**Comment by maxidigi** [comment]
Thank you.  This was very helpful.
